### ISSUE TITLE
Support Docker image installation

### ISSUE THREAD

**Issue by mmm8955405** [texm/shokku#6]
Support Docker image installation

**Comment by texm** [comment]
Hi, this should already be possible. The [bootstrap script](https://github.com/texm/shokku/blob/main/bootstrap.sh) is basically pulling the docker image and running it under Dokku. 

If there is a desire for documentation on doing this without using Dokku I could write something up.

**Comment by mmm8955405** [comment]
Add the documentation for Docker installation as soon as possible
